# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Repeater' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Repeater
  pod 'Firebase/Auth'
  pod 'Firebase/Analytics'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  pod 'Firebase/Messaging'
  pod 'Firebase/Functions'
  
  pod 'ASCollectionView-SwiftUI'
  pod 'MagazineLayout'

end
